version: '3.2'

services:

  api:
    container_name: api
    build: ./api
    ports:
      - 8080:80
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    build: ./db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
