version: '3.2'

services:

  api:
    container_name: api
    build: ./api
    ports:
      - 8080:80
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    build: ./db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: secret
    ports:
      - 54321:5432
